sudo: required

language: python

python:
  - 3.6

services: 
  - docker

install:
  - git clone https://github.com/ubclaunchpad/sleuth-frontend.git ../sleuth-frontend
  - docker-compose up

script:
  - docker-compose exec web "python manage.py test sleuth_backend.tests && python manage.py test sleuth_crawler.tests"