sudo: required

language: python

python:
  - 3.6

services: 
  - docker

install:
  - git clone https://github.com/ubclaunchpad/sleuth-frontend.git ../sleuth-frontend
  - docker-compose build

script:
  - docker-compose run web "bash scripts/startup.sh && python manage.py test sleuth_backend.tests && python manage.py test sleuth_crawler.tests"