sudo: required

language: python

python:
  - 3.6

services: 
  - docker
  - postgres

install:
  - git clone https://github.com/ubclaunchpad/sleuth-frontend.git ../sleuth-frontend
  - docker-compose up -d solr
  - pip install -r requirements.txt
  - python scripts/nltk_setup.py
  - bash scripts/wait.sh "Solr" "curl localhost:8983/solr"

before_script:
  - psql -c 'create database testdb;' -U postgres

script:
  - python manage.py test

after_script:
  - coveralls