sudo: required

language: python

python:
  - 3.6

services: 
  - docker
  - postgres

install:
  - docker-compose up solr
  - pip install -r requirements.txt
  - bash scripts/wait.sh "curl solr:8983/solr"

before_script:
  - psql -c 'create database testdb;' -U postgres

script:
  - python manage.py test