language: python

python:
  - 3.6

services: 
  - postgresql

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE testdb;" -U postgres

script:
  - python manage.py test sleuth_backend.tests
  - python manage.py test sleuth_crawler.tests