version: '3'

services:
  db:
    image: postgres

  solr:
    image: solr
    ports:
     - "8983:8983"
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - test

  web:
    environment: 
     - PYTHONUNBUFFERED=1
    build: .
    command: bash scripts/startup.sh
    volumes:
      - .:/home/sleuth
    ports:
      - "8000:8000"
    depends_on:
      - db
      - solr

  frontend:
    build: 
      context: ../sleuth-frontend
    command: yarn start --host 0.0.0.0 --port 8080
    volumes:
      - ../sleuth-frontend:/home/sleuth-frontend
    ports: 
      - "8080:8080"
    depends_on:
      - web